services:
  pingvin-share:
    image: stonith404/pingvin-share # or ghcr.io/stonith404/pingvin-share
    restart: unless-stopped
    environment:
      - TRUST_PROXY=true # Set to true if a reverse proxy is in front of the container
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - INIT_USERNAME=${INIT_USERNAME}
      - INIT_EMAIL=${INIT_EMAIL}
      - INIT_PASS=${INIT_PASS}
    volumes:
      - "./data:/opt/app/backend/data"
      - "./data/images:/opt/app/frontend/public/img"
      - "./config.custom.yaml:/opt/app/config.yaml" # Add this line, if you want to configure pingvin-share via config file and not via UI

  # To add ClamAV, to scan your shares for malicious files, 
  # see https://stonith404.github.io/pingvin-share/setup/integrations/#clamav-docker-only
